// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attendee.proto

package com.voxxed.bristol.pojo;

public final class AttendeeProto {
  private AttendeeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AttendeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:voxxed.bristol.Attendee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string first_name = 1;</code>
     */
    boolean hasFirstName();
    /**
     * <code>required string first_name = 1;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>required string first_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>required string last_name = 2;</code>
     */
    boolean hasLastName();
    /**
     * <code>required string last_name = 2;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>required string last_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>optional .voxxed.bristol.Attendee.Address address = 3;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional .voxxed.bristol.Attendee.Address address = 3;</code>
     */
    com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address getAddress();
    /**
     * <code>optional .voxxed.bristol.Attendee.Address address = 3;</code>
     */
    com.voxxed.bristol.pojo.AttendeeProto.Attendee.AddressOrBuilder getAddressOrBuilder();
  }
  /**
   * Protobuf type {@code voxxed.bristol.Attendee}
   */
  public  static final class Attendee extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:voxxed.bristol.Attendee)
      AttendeeOrBuilder {
    // Use Attendee.newBuilder() to construct.
    private Attendee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Attendee() {
      firstName_ = "";
      lastName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Attendee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              firstName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              lastName_ = bs;
              break;
            }
            case 26: {
              com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = address_.toBuilder();
              }
              address_ = input.readMessage(com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(address_);
                address_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.voxxed.bristol.pojo.AttendeeProto.internal_static_voxxed_bristol_Attendee_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.voxxed.bristol.pojo.AttendeeProto.internal_static_voxxed_bristol_Attendee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.voxxed.bristol.pojo.AttendeeProto.Attendee.class, com.voxxed.bristol.pojo.AttendeeProto.Attendee.Builder.class);
    }

    public interface AddressOrBuilder extends
        // @@protoc_insertion_point(interface_extends:voxxed.bristol.Attendee.Address)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string city = 1;</code>
       */
      boolean hasCity();
      /**
       * <code>required string city = 1;</code>
       */
      java.lang.String getCity();
      /**
       * <code>required string city = 1;</code>
       */
      com.google.protobuf.ByteString
          getCityBytes();

      /**
       * <code>required string street = 2;</code>
       */
      boolean hasStreet();
      /**
       * <code>required string street = 2;</code>
       */
      java.lang.String getStreet();
      /**
       * <code>required string street = 2;</code>
       */
      com.google.protobuf.ByteString
          getStreetBytes();

      /**
       * <code>required int32 number = 3;</code>
       */
      boolean hasNumber();
      /**
       * <code>required int32 number = 3;</code>
       */
      int getNumber();
    }
    /**
     * Protobuf type {@code voxxed.bristol.Attendee.Address}
     */
    public  static final class Address extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:voxxed.bristol.Attendee.Address)
        AddressOrBuilder {
      // Use Address.newBuilder() to construct.
      private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Address() {
        city_ = "";
        street_ = "";
        number_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Address(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                city_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                street_ = bs;
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                number_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.voxxed.bristol.pojo.AttendeeProto.internal_static_voxxed_bristol_Attendee_Address_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.voxxed.bristol.pojo.AttendeeProto.internal_static_voxxed_bristol_Attendee_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.class, com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.Builder.class);
      }

      private int bitField0_;
      public static final int CITY_FIELD_NUMBER = 1;
      private volatile java.lang.Object city_;
      /**
       * <code>required string city = 1;</code>
       */
      public boolean hasCity() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string city = 1;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            city_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string city = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int STREET_FIELD_NUMBER = 2;
      private volatile java.lang.Object street_;
      /**
       * <code>required string street = 2;</code>
       */
      public boolean hasStreet() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string street = 2;</code>
       */
      public java.lang.String getStreet() {
        java.lang.Object ref = street_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            street_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string street = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStreetBytes() {
        java.lang.Object ref = street_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          street_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int NUMBER_FIELD_NUMBER = 3;
      private int number_;
      /**
       * <code>required int32 number = 3;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 number = 3;</code>
       */
      public int getNumber() {
        return number_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasCity()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasStreet()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasNumber()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, city_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, street_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, number_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, city_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, street_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, number_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address)) {
          return super.equals(obj);
        }
        com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address other = (com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address) obj;

        boolean result = true;
        result = result && (hasCity() == other.hasCity());
        if (hasCity()) {
          result = result && getCity()
              .equals(other.getCity());
        }
        result = result && (hasStreet() == other.hasStreet());
        if (hasStreet()) {
          result = result && getStreet()
              .equals(other.getStreet());
        }
        result = result && (hasNumber() == other.hasNumber());
        if (hasNumber()) {
          result = result && (getNumber()
              == other.getNumber());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        if (hasCity()) {
          hash = (37 * hash) + CITY_FIELD_NUMBER;
          hash = (53 * hash) + getCity().hashCode();
        }
        if (hasStreet()) {
          hash = (37 * hash) + STREET_FIELD_NUMBER;
          hash = (53 * hash) + getStreet().hashCode();
        }
        if (hasNumber()) {
          hash = (37 * hash) + NUMBER_FIELD_NUMBER;
          hash = (53 * hash) + getNumber();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code voxxed.bristol.Attendee.Address}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:voxxed.bristol.Attendee.Address)
          com.voxxed.bristol.pojo.AttendeeProto.Attendee.AddressOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.voxxed.bristol.pojo.AttendeeProto.internal_static_voxxed_bristol_Attendee_Address_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.voxxed.bristol.pojo.AttendeeProto.internal_static_voxxed_bristol_Attendee_Address_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.class, com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.Builder.class);
        }

        // Construct using com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          city_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          street_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          number_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.voxxed.bristol.pojo.AttendeeProto.internal_static_voxxed_bristol_Attendee_Address_descriptor;
        }

        public com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address getDefaultInstanceForType() {
          return com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.getDefaultInstance();
        }

        public com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address build() {
          com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address buildPartial() {
          com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address result = new com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.city_ = city_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.street_ = street_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.number_ = number_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address) {
            return mergeFrom((com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address other) {
          if (other == com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.getDefaultInstance()) return this;
          if (other.hasCity()) {
            bitField0_ |= 0x00000001;
            city_ = other.city_;
            onChanged();
          }
          if (other.hasStreet()) {
            bitField0_ |= 0x00000002;
            street_ = other.street_;
            onChanged();
          }
          if (other.hasNumber()) {
            setNumber(other.getNumber());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasCity()) {
            return false;
          }
          if (!hasStreet()) {
            return false;
          }
          if (!hasNumber()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object city_ = "";
        /**
         * <code>required string city = 1;</code>
         */
        public boolean hasCity() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string city = 1;</code>
         */
        public java.lang.String getCity() {
          java.lang.Object ref = city_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              city_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string city = 1;</code>
         */
        public com.google.protobuf.ByteString
            getCityBytes() {
          java.lang.Object ref = city_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            city_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string city = 1;</code>
         */
        public Builder setCity(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          city_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string city = 1;</code>
         */
        public Builder clearCity() {
          bitField0_ = (bitField0_ & ~0x00000001);
          city_ = getDefaultInstance().getCity();
          onChanged();
          return this;
        }
        /**
         * <code>required string city = 1;</code>
         */
        public Builder setCityBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          city_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object street_ = "";
        /**
         * <code>required string street = 2;</code>
         */
        public boolean hasStreet() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string street = 2;</code>
         */
        public java.lang.String getStreet() {
          java.lang.Object ref = street_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              street_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string street = 2;</code>
         */
        public com.google.protobuf.ByteString
            getStreetBytes() {
          java.lang.Object ref = street_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            street_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string street = 2;</code>
         */
        public Builder setStreet(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          street_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string street = 2;</code>
         */
        public Builder clearStreet() {
          bitField0_ = (bitField0_ & ~0x00000002);
          street_ = getDefaultInstance().getStreet();
          onChanged();
          return this;
        }
        /**
         * <code>required string street = 2;</code>
         */
        public Builder setStreetBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          street_ = value;
          onChanged();
          return this;
        }

        private int number_ ;
        /**
         * <code>required int32 number = 3;</code>
         */
        public boolean hasNumber() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required int32 number = 3;</code>
         */
        public int getNumber() {
          return number_;
        }
        /**
         * <code>required int32 number = 3;</code>
         */
        public Builder setNumber(int value) {
          bitField0_ |= 0x00000004;
          number_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 number = 3;</code>
         */
        public Builder clearNumber() {
          bitField0_ = (bitField0_ & ~0x00000004);
          number_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:voxxed.bristol.Attendee.Address)
      }

      // @@protoc_insertion_point(class_scope:voxxed.bristol.Attendee.Address)
      private static final com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address();
      }

      public static com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Address>
          PARSER = new com.google.protobuf.AbstractParser<Address>() {
        public Address parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Address(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Address> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Address> getParserForType() {
        return PARSER;
      }

      public com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int FIRST_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object firstName_;
    /**
     * <code>required string first_name = 1;</code>
     */
    public boolean hasFirstName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string first_name = 1;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string first_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object lastName_;
    /**
     * <code>required string last_name = 2;</code>
     */
    public boolean hasLastName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string last_name = 2;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string last_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address address_;
    /**
     * <code>optional .voxxed.bristol.Attendee.Address address = 3;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .voxxed.bristol.Attendee.Address address = 3;</code>
     */
    public com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address getAddress() {
      return address_ == null ? com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.getDefaultInstance() : address_;
    }
    /**
     * <code>optional .voxxed.bristol.Attendee.Address address = 3;</code>
     */
    public com.voxxed.bristol.pojo.AttendeeProto.Attendee.AddressOrBuilder getAddressOrBuilder() {
      return address_ == null ? com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.getDefaultInstance() : address_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFirstName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAddress()) {
        if (!getAddress().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getAddress());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getAddress());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.voxxed.bristol.pojo.AttendeeProto.Attendee)) {
        return super.equals(obj);
      }
      com.voxxed.bristol.pojo.AttendeeProto.Attendee other = (com.voxxed.bristol.pojo.AttendeeProto.Attendee) obj;

      boolean result = true;
      result = result && (hasFirstName() == other.hasFirstName());
      if (hasFirstName()) {
        result = result && getFirstName()
            .equals(other.getFirstName());
      }
      result = result && (hasLastName() == other.hasLastName());
      if (hasLastName()) {
        result = result && getLastName()
            .equals(other.getLastName());
      }
      result = result && (hasAddress() == other.hasAddress());
      if (hasAddress()) {
        result = result && getAddress()
            .equals(other.getAddress());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasFirstName()) {
        hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getFirstName().hashCode();
      }
      if (hasLastName()) {
        hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getLastName().hashCode();
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.voxxed.bristol.pojo.AttendeeProto.Attendee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.voxxed.bristol.pojo.AttendeeProto.Attendee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.voxxed.bristol.pojo.AttendeeProto.Attendee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.voxxed.bristol.pojo.AttendeeProto.Attendee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.voxxed.bristol.pojo.AttendeeProto.Attendee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.voxxed.bristol.pojo.AttendeeProto.Attendee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.voxxed.bristol.pojo.AttendeeProto.Attendee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.voxxed.bristol.pojo.AttendeeProto.Attendee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.voxxed.bristol.pojo.AttendeeProto.Attendee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.voxxed.bristol.pojo.AttendeeProto.Attendee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.voxxed.bristol.pojo.AttendeeProto.Attendee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code voxxed.bristol.Attendee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:voxxed.bristol.Attendee)
        com.voxxed.bristol.pojo.AttendeeProto.AttendeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.voxxed.bristol.pojo.AttendeeProto.internal_static_voxxed_bristol_Attendee_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.voxxed.bristol.pojo.AttendeeProto.internal_static_voxxed_bristol_Attendee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.voxxed.bristol.pojo.AttendeeProto.Attendee.class, com.voxxed.bristol.pojo.AttendeeProto.Attendee.Builder.class);
      }

      // Construct using com.voxxed.bristol.pojo.AttendeeProto.Attendee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAddressFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        firstName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        lastName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (addressBuilder_ == null) {
          address_ = null;
        } else {
          addressBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.voxxed.bristol.pojo.AttendeeProto.internal_static_voxxed_bristol_Attendee_descriptor;
      }

      public com.voxxed.bristol.pojo.AttendeeProto.Attendee getDefaultInstanceForType() {
        return com.voxxed.bristol.pojo.AttendeeProto.Attendee.getDefaultInstance();
      }

      public com.voxxed.bristol.pojo.AttendeeProto.Attendee build() {
        com.voxxed.bristol.pojo.AttendeeProto.Attendee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.voxxed.bristol.pojo.AttendeeProto.Attendee buildPartial() {
        com.voxxed.bristol.pojo.AttendeeProto.Attendee result = new com.voxxed.bristol.pojo.AttendeeProto.Attendee(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.firstName_ = firstName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lastName_ = lastName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (addressBuilder_ == null) {
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.voxxed.bristol.pojo.AttendeeProto.Attendee) {
          return mergeFrom((com.voxxed.bristol.pojo.AttendeeProto.Attendee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.voxxed.bristol.pojo.AttendeeProto.Attendee other) {
        if (other == com.voxxed.bristol.pojo.AttendeeProto.Attendee.getDefaultInstance()) return this;
        if (other.hasFirstName()) {
          bitField0_ |= 0x00000001;
          firstName_ = other.firstName_;
          onChanged();
        }
        if (other.hasLastName()) {
          bitField0_ |= 0x00000002;
          lastName_ = other.lastName_;
          onChanged();
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFirstName()) {
          return false;
        }
        if (!hasLastName()) {
          return false;
        }
        if (hasAddress()) {
          if (!getAddress().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.voxxed.bristol.pojo.AttendeeProto.Attendee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.voxxed.bristol.pojo.AttendeeProto.Attendee) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object firstName_ = "";
      /**
       * <code>required string first_name = 1;</code>
       */
      public boolean hasFirstName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string first_name = 1;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            firstName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string first_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string first_name = 1;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string first_name = 1;</code>
       */
      public Builder clearFirstName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>required string first_name = 1;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>required string last_name = 2;</code>
       */
      public boolean hasLastName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string last_name = 2;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lastName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string last_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string last_name = 2;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string last_name = 2;</code>
       */
      public Builder clearLastName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>required string last_name = 2;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lastName_ = value;
        onChanged();
        return this;
      }

      private com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address address_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address, com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.Builder, com.voxxed.bristol.pojo.AttendeeProto.Attendee.AddressOrBuilder> addressBuilder_;
      /**
       * <code>optional .voxxed.bristol.Attendee.Address address = 3;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .voxxed.bristol.Attendee.Address address = 3;</code>
       */
      public com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address getAddress() {
        if (addressBuilder_ == null) {
          return address_ == null ? com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.getDefaultInstance() : address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .voxxed.bristol.Attendee.Address address = 3;</code>
       */
      public Builder setAddress(com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
          onChanged();
        } else {
          addressBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .voxxed.bristol.Attendee.Address address = 3;</code>
       */
      public Builder setAddress(
          com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
          onChanged();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .voxxed.bristol.Attendee.Address address = 3;</code>
       */
      public Builder mergeAddress(com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address value) {
        if (addressBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              address_ != null &&
              address_ != com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.getDefaultInstance()) {
            address_ =
              com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.newBuilder(address_).mergeFrom(value).buildPartial();
          } else {
            address_ = value;
          }
          onChanged();
        } else {
          addressBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .voxxed.bristol.Attendee.Address address = 3;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = null;
          onChanged();
        } else {
          addressBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .voxxed.bristol.Attendee.Address address = 3;</code>
       */
      public com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.Builder getAddressBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .voxxed.bristol.Attendee.Address address = 3;</code>
       */
      public com.voxxed.bristol.pojo.AttendeeProto.Attendee.AddressOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_ == null ?
              com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.getDefaultInstance() : address_;
        }
      }
      /**
       * <code>optional .voxxed.bristol.Attendee.Address address = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address, com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.Builder, com.voxxed.bristol.pojo.AttendeeProto.Attendee.AddressOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address, com.voxxed.bristol.pojo.AttendeeProto.Attendee.Address.Builder, com.voxxed.bristol.pojo.AttendeeProto.Attendee.AddressOrBuilder>(
                  getAddress(),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:voxxed.bristol.Attendee)
    }

    // @@protoc_insertion_point(class_scope:voxxed.bristol.Attendee)
    private static final com.voxxed.bristol.pojo.AttendeeProto.Attendee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.voxxed.bristol.pojo.AttendeeProto.Attendee();
    }

    public static com.voxxed.bristol.pojo.AttendeeProto.Attendee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Attendee>
        PARSER = new com.google.protobuf.AbstractParser<Attendee>() {
      public Attendee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Attendee(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Attendee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Attendee> getParserForType() {
      return PARSER;
    }

    public com.voxxed.bristol.pojo.AttendeeProto.Attendee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_voxxed_bristol_Attendee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_voxxed_bristol_Attendee_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_voxxed_bristol_Attendee_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_voxxed_bristol_Attendee_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016attendee.proto\022\016voxxed.bristol\"\235\001\n\010Att" +
      "endee\022\022\n\nfirst_name\030\001 \002(\t\022\021\n\tlast_name\030\002" +
      " \002(\t\0221\n\007address\030\003 \001(\0132 .voxxed.bristol.A" +
      "ttendee.Address\0327\n\007Address\022\014\n\004city\030\001 \002(\t" +
      "\022\016\n\006street\030\002 \002(\t\022\016\n\006number\030\003 \002(\005B(\n\027com." +
      "voxxed.bristol.pojoB\rAttendeeProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_voxxed_bristol_Attendee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_voxxed_bristol_Attendee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_voxxed_bristol_Attendee_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Address", });
    internal_static_voxxed_bristol_Attendee_Address_descriptor =
      internal_static_voxxed_bristol_Attendee_descriptor.getNestedTypes().get(0);
    internal_static_voxxed_bristol_Attendee_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_voxxed_bristol_Attendee_Address_descriptor,
        new java.lang.String[] { "City", "Street", "Number", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
